---
name: 💥 Regression Report
description: Report unexpected behavior that worked in previous versions
labels: ["regression :boom:"]
assignees:
  - felddy
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this regression report!
  - type: textarea
    id: description
    attributes:
      label: Regression description
      description: A clear and concise description of what the regression is.
      placeholder: |
        The object color selector used to list purple.  Now it does not.
    validations:
      required: true
  - type: input
    id: worked-up-to-version
    attributes:
      label: Worked up to version
      description: What was the last version that was working?
      placeholder: x.y.z
    validations:
      required: true
  - type: input
    id: stopped-working-in-version
    attributes:
      label: Stopped working in version
      description: What version did it stop working in?
      placeholder: x.y.z
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: What are the steps to reproduce the behavior?
      placeholder: |
        - Select an object on the page.
        - Right-click on the selected object.
        - Choose a color from the color change popup menu.
        - Notice purple is not in the list.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: |
        I expect that purple would be in the color selection list.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Use the following command to print your container metadata:

        ```bash
        docker inspect --format='{{range $k, $v := .Config.Labels}}
            {{- printf "%s = \"%s\"\n" $k $v -}} {{end}}' \
            felddy/foundryvtt:release
        ```
  - type: textarea
    id: container-metadata
    attributes:
      label: Container metadata
      description: Paste the output from the command above. This will be automatically formatted, so no need for backticks.
      render: shell
      placeholder: |
        com.foundryvtt.version = "12.331"
        org.opencontainers.image.authors = "markf+github@geekpad.com"
        org.opencontainers.image.created = "2022-09-01T23:22:04.337Z"
        org.opencontainers.image.description = "An easy-to-deploy Dockerized Foundry Virtual Tabletop server."
        org.opencontainers.image.licenses = "MIT"
        org.opencontainers.image.revision = "94d5cc47fc0c5ac5ae268988c6673c046e39e6b6"
        org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker"
        org.opencontainers.image.title = "foundryvtt-docker"
        org.opencontainers.image.url = "https://github.com/felddy/foundryvtt-docker"
        org.opencontainers.image.vendor = "Geekpad"
        org.opencontainers.image.version = "12.331.0"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Run the container with `CONTAINER_VERBOSE` set to `true`,and paste any useful log output. This will be automatically formatted into code, so no need for backticks.
      render: console
      placeholder: |
        foundry_1   | Entrypoint | 2022-02-23 14:14:53 | [debug] Timezone set to: US/Eastern
        foundry_1   | Entrypoint | 2022-02-23 14:14:53 | [info] Starting felddy/foundryvtt container v12.331.0
        foundry_1   | Entrypoint | 2022-02-23 14:14:53 | [debug] CONTAINER_VERBOSE set.  Debug logging enabled.
        foundry_1   | Entrypoint | 2022-02-23 14:14:53 | [info] Reading configured secrets from: /run/secrets/config.json
        foundry_1   | Entrypoint | 2022-02-23 14:14:53 | [info] No Foundry Virtual Tabletop installation detected.
        foundry_1   | Entrypoint | 2022-02-23 14:14:53 | [info] Using FOUNDRY_USERNAME and FOUNDRY_PASSWORD to authenticate.
        foundry_1   | Authenticate | 2022-02-23 14:14:54 | [debug] Saving cookies to: cookiejar.json
        foundry_1   | Authenticate | 2022-02-23 14:14:54 | [info] Requesting CSRF tokens from https://foundryvtt.com
        foundry_1   | Authenticate | 2022-02-23 14:14:54 | [debug] Fetching: https://foundryvtt.com
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/felddy/foundryvtt-docker/blob/develop/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
