---
name: Config

permissions: {}

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      platforms:
        description: The platforms to build (JSON array string)
        default: >-
          ["linux/amd64","linux/arm64","linux/ppc64le","linux/s390x"]
        required: false
        type: string
    outputs:
      container_version:
        description: The container version from src/version.txt
        value: ${{ jobs.config.outputs.container_version }}
      foundry_version:
        description: The derived Foundry major.build version
        value: ${{ jobs.config.outputs.foundry_version }}
      image_name:
        description: The container image name
        value: felddy/foundryvtt
      image_name_preinstall:
        description: The pre-install container image name
        value: felddy/foundryvtt-preinstall
      platforms:
        description: The platforms to build (JSON array string)
        value: ${{ inputs.platforms }}
      test_platforms:
        description: The platform to use for testing (JSON array string)
        value: '["linux/amd64"]'

jobs:
  config:
    name: Configuration
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      container_version: ${{ steps.version.outputs.container_version }}
      foundry_version: ${{ steps.version.outputs.foundry_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # tag=v7.0.1
      - name: Emit version outputs
        id: version
        run: make github-output >> "$GITHUB_OUTPUT"
