---

name: Scorecards supply-chain security

on:
  # Only the default branch is supported.
  branch_protection_rule:
  schedule:
    - cron: '43 4 * * 0'
  push:
    branches: [develop]

# Declare default permissions as read only.
permissions: read-all

jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      actions: read
      contents: read

    steps:
      - name: "Checkout code"
        # v3.0.0
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          persist-credentials: false

      - name: "Run analysis"
        # v1.0.4
        uses: ossf/scorecard-action@ce330fde6b1a5c9c75b417e7efc510b822a35564
        with:
          results_file: results.sarif
          results_format: sarif
          # Read-only PAT token. To create it, follow the steps in
          # https://github.com/ossf/scorecard-action#pat-token-creation.
          repo_token: ${{ secrets.SCORECARD_READ_TOKEN }}
          # Publish the results to enable scorecard badges. For more details,
          # see https://github.com/ossf/scorecard-action#publishing-results. For
          # private repositories, `publish_results` will automatically be set to
          # `false`, regardless of the value entered here.
          publish_results: true

      # Upload the results as artifacts (optional).
      - name: "Upload artifact"
        # v3.0.0
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      # Upload the results to GitHub's code scanning dashboard.
      - name: "Upload to code-scanning"
        # v1.0.26
        uses: github/codeql-action/upload-sarif@f5d217be74900c6ac8fbbe53f3c10376ba4e64da
        with:
          sarif_file: results.sarif
