---
name: Label and close stale issues

on:
  schedule:
    - cron: '0 10 * * *'  # everyday at 10am
  workflow_dispatch:

permissions:
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2  # tag=v2.13.2
        with:
          egress-policy: audit  # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/stale@5f858e3efba33a5ca4407a664cc011ad407f2008  # tag=v10.1.0
        with:
          days-before-stale: 28
          days-before-close: 7
          stale-issue-message: >-
            This issue has been automatically marked as stale because it has been
            inactive for 28 days. To reactivate the issue, simply post a comment
            with the requested information to help us diagnose this issue. If this
            issue remains inactive for another 7 days, it will be automatically
            closed.
          close-issue-message: >-
            This issue has been automatically closed due to inactivity. If you are
            still experiencing problems, please open a new issue.
          stale-issue-label: "stale :skull:"
          only-labels: "needs more info :thinking:"
